### ISSUE TITLE
Input validation before saving data

### ISSUE THREAD

**Issue by ad3n** [rawaludin/draft#1]
Dari sini

https://github.com/rahmatawaludin/draft/blob/master/app%2Fcontrollers%2FUsersController.php#L28

ke sini

https://github.com/rahmatawaludin/draft/blob/master/app%2Fmodels%2FUserRepository.php#L20

kok tidak ada validasinya ya?

**Comment by rawaludin** [comment]
Sudah ada mas. Cek di trait ConfideUser.
